#!/usr/bin/python

from dota2info import helpers
import json
import sys

"""
reads .demsonraw file

prints plottable data regarding damage dealt between different factions (neutrals, creeps , heroes (radiant/dire)
illusions as own type?
"""

events = []
actors = {}

def maybeAddToActorDict(actorStringId):
    if actorStringId not in actors:
        actors[actorStringId] = {"stringId": actorStringId, "id": len(actors)}
    return actors[actorStringId]["id"]

replay = map(json.loads, sys.stdin)
combatlogs_tr = helpers.getCombatlogsTranslated(replay)

for e in combatlogs_tr:
    #right now, only kills are delivered
    f = e["attackername"]
    t = e["targetname"]

    #TODO: translate the string to factions
    #output the list of all factions / subfactions (radiant, heroes, creeptypes, fortifications?) with ids so they can be easily addressed?
    # example possible items
    # idString=... name = lina, subfaction = heroes, faction = radiant
    # idString=... name = whocares, subfaction = creeps, faction = neutral
    # idString=... name = melee, subfaction = creeps, faction = neutral
    # idString=... name = melee_mega, subfaction = creeps, faction = neutral
    fId = maybeAddToActorDict(f)
    tId = maybeAddToActorDict(t)

    #TODO: accumulate events into time bins if the data turns out to be unwieldy
    when = e["timestamp"] #TODO: round to some discrete time measure?

    if e["type"] == 4:
        events.append({ "what": "kill",
                        "when": when,
                        "from": fId,
                        "to": tId})

actorsById = {}

#so json can look up information in each event
for stringId,v in actors.iteritems():
    actorsById[v["id"]] = v

#output actual events (when what happens to whom of what factions)
data = { "actors": actorsById,
        "events": events
       }
print(json.dumps(data))
